### ISSUE TITLE
[common] Wrapping CUDA stream in another class to catch stream destruction

### ISSUE THREAD

**Issue by tijyojwad** [clara-parabricks/GenomeWorks#393]

**Comment by tijyojwad** [comment]
@ahehn-nv - can you fill in the details for this task?

**Comment by ahehn-nv** [comment]
Here are the details: We encounter cases (during development) where we see an cudaErrorContextIsDestroyed (or similar) in the pre-allocated allocator.
The problem is that the stream gets destroyed (manually) before the buffer associated with the stream gets deallocated - leading to a cudaStreamSynchronize on a freed/invalid stream handle in the pre-allocated allocator. The reason for this is that while the buffer (created with the pre-allocated allocator) gets destroyed automatically by C++ when execution leave the scope, the cudaStream gets (created and) destroyed manually via `cudaStreamDestroy(steam)`. Therefore, for a stream and a buffer created and destroyed in the same scope, the buffer will always be deleted after the associated stream, since you have to call `cudaStreamDestroy(stream);` before the end of the scope.

**Comment by ahehn-nv** [comment]
A possible solution is wrapping the stream in a RAII class, such that it also gets automatically destroyed when leaving scope. A good starting point is in https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/dev-v0.5.0/cudaaligner/benchmarks/main.cpp#L59 which needs some polishing, be moved to common/base/utils/ and used wherever we create a stream.

**Comment by tijyojwad** [comment]
Hi @rached-ab - jsut wanted to check on the status of this issue and if there's anything we can help you with

**Comment by rached-ab** [comment]
Hi @tijyojwad, I will start working today on the issue. Touched base with Milos to get more elements about the issue.
